select 
t.task_id,
t.actual_end_dttm,
t.actual_start_dttm,
t.description,
t.person_id,
p.email_address,
t.task_status,
t.task_template_id,
t.task_type,
r.request_id,
r.req_class,
r.created_dttm,
iif(t.person_id in ('ALMIEG',	'ALMIFELLES',	'ALMIJDM',	'ALMIJJ',	'ALMILIA',	'BECHTVE',	'BEFIB',	'BEFRESP',	'BEJOELL',	'BEJOHAR',	'BEKOAX',	'BEKOM',	'BEPALEV',	'BESIHAU',	'BETRBOR',	'BNORMANN',	'BOMABOR',	'BRARENG',	'BRTHJOH',	'BRTRSOR',	'ENANHOL',	'ENARBER',	'ENARDAH',	'ENEVSKJ',	'ENJAHAM',	'ENKEFRI',	'ENKENIL',	'ENKRGUS',	'ENKRVEN',	'ENMAMOE',	'ENMAVAL',	'ENORINSTALL',	'ENTHGRA',	'FOSTFRØ',	'GFALDAL',	'GFANALF',	'GFANAMI',	'GFERGUS',	'GFERKUL',	'GFHAKLE',	'GFJOKVI',	'GFPOKRI',	'GFTHMEL',	'GFVIGUS',	'GTJOSER',	'GTJOVOL',	'GTKERAU',	'GTPRBOC',	'GTRUJOH',	'HAALLUN',	'HAEHJAY',	'HAKAHAG',	'HAKALAR',	'HAKAPIW',	'HAMAHEI',	'HAMIKOM',	'HANESETHHARSTAD',	'HANESETHHARSTAD2',	'HANESETHNARVIK',	'HAORKRI',	'HAROHAN',	'HASAKAR',	'HASHSCH',	'HAVIBER',	'LIKOSMI',	'MFCHTER',	'MIDAFLA',	'MIHAOPD',	'MIHATOD',	'MIJOGRO',	'MITOLAE',	'MIVEGRA',	'MIVEGUS',	'MOKEKVA',	'NCANSOL',	'NCANTOR',	'NCBJNOR',	'NCESNED',	'NCIVNJA',	'NCJAHJE',	'NCJONOR',	'NCKAASOL',	'NCKEKIR',	'NCKIJON',	'NCKNBJE',	'NCLASOL',	'NCLATHO',	'NCLEBRA',	'NCLETAN',	'NCMABUR',	'NCMOAMU',	'NCPEAMU',	'NCPELIE',	'NCPENAR',	'NCROPET',	'NCRUSUS',	'NCSIGRU',	'NCSTJOH',	'NCSTPED',	'NCTEAMU',	'REJEMON',	'REKNMYK',	'REMAAAD',	'REREMON',	'RESTRAU',	'SIBRVUT',	'SIHAGUL',	'SIJOMUN',	'SILAHEP',	'SILALAR',	'SILILAU',	'SIMASOR',	'SIPRKRI',	'SISTHOL',	'TMFISKO',	'TMHEMOD',	'TMMAJAN',	'TMTHBER',	'VAARVIKEN'), 'UE','Eltel'),
p.user_def12 as Avdeling

from task t
left join request r on t.request_id = r.request_id
left join person p on t.person_id = p.person_id

where --t.person_id in ('ALMIEG',	'ALMIFELLES',	'ALMIJDM',	'ALMIJJ',	'ALMILIA',	'BECHTVE',	'BEFIB',	'BEFRESP',	'BEJOELL',	'BEJOHAR',	'BEKOAX',	'BEKOM',	'BEPALEV',	'BESIHAU',	'BETRBOR',	'BNORMANN',	'BOMABOR',	'BRARENG',	'BRTHJOH',	'BRTRSOR',	'ENANHOL',	'ENARBER',	'ENARDAH',	'ENEVSKJ',	'ENJAHAM',	'ENKEFRI',	'ENKENIL',	'ENKRGUS',	'ENKRVEN',	'ENMAMOE',	'ENMAVAL',	'ENORINSTALL',	'ENTHGRA',	'FOSTFRØ',	'GFALDAL',	'GFANALF',	'GFANAMI',	'GFERGUS',	'GFERKUL',	'GFHAKLE',	'GFJOKVI',	'GFPOKRI',	'GFTHMEL',	'GFVIGUS',	'GTJOSER',	'GTJOVOL',	'GTKERAU',	'GTPRBOC',	'GTRUJOH',	'HAALLUN',	'HAEHJAY',	'HAKAHAG',	'HAKALAR',	'HAKAPIW',	'HAMAHEI',	'HAMIKOM',	'HANESETHHARSTAD',	'HANESETHHARSTAD2',	'HANESETHNARVIK',	'HAORKRI',	'HAROHAN',	'HASAKAR',	'HASHSCH',	'HAVIBER',	'LIKOSMI',	'MFCHTER',	'MIDAFLA',	'MIHAOPD',	'MIHATOD',	'MIJOGRO',	'MITOLAE',	'MIVEGRA',	'MIVEGUS',	'MOKEKVA',	'NCANSOL',	'NCANTOR',	'NCBJNOR',	'NCESNED',	'NCIVNJA',	'NCJAHJE',	'NCJONOR',	'NCKAASOL',	'NCKEKIR',	'NCKIJON',	'NCKNBJE',	'NCLASOL',	'NCLATHO',	'NCLEBRA',	'NCLETAN',	'NCMABUR',	'NCMOAMU',	'NCPEAMU',	'NCPELIE',	'NCPENAR',	'NCROPET',	'NCRUSUS',	'NCSIGRU',	'NCSTJOH',	'NCSTPED',	'NCTEAMU',	'REJEMON',	'REKNMYK',	'REMAAAD',	'REREMON',	'RESTRAU',	'SIBRVUT',	'SIHAGUL',	'SIJOMUN',	'SILAHEP',	'SILALAR',	'SILILAU',	'SIMASOR',	'SIPRKRI',	'SISTHOL',	'TMFISKO',	'TMHEMOD',	'TMMAJAN',	'TMTHBER',	'VAARVIKEN')
r.created_dttm >= '2021-09-01' and t.person_id is not null